apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtr.fullname" . }}
  labels:
    access: internal
    app: {{ .Chart.Name }}
    {{- include "rtr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      {{- include "rtr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        access: internal
        app: {{ .Chart.Name }}
        {{- include "rtr.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.useImageSecrets }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "rtr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          volumeMounts:
            #- mountPath: /etc/pki/application
            #  name: application-pki-volume
            - mountPath: /etc/nginx/nginx.conf
              name: {{ .Chart.Name }}-nginx-config
              subPath: https.conf
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: kubedemo
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
      volumes:
        #- name: application-pki-volume
        #  secret:
        #    secretName: "k8s-cerebro-ltac-ssl"
        - name: {{ .Chart.Name }}-nginx-config
          configMap:
            name: {{ .Chart.Name }}-nginx-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
