# Default values for cerebro.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  replicaCount: 1

  # imagePullSecrets needed for private repo should
  useImageSecrets: true
  imagePullSecrets:
  - name: regcred

  airgapped: false
  image:
    repository: registry.levelup.cce.af.mil/plorentz/kubedemo/
    # repository: harbor.defenders.dev/kubedemo/
    # repository: ltac.dev.local:5000/
    pullPolicy: IfNotPresent

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # resources to set if required by installation infrastructure
  # recommended to not set these values unless it is needed
  resources: {}
    # limits:
    #   cpu: 120m
    #   memory: 500Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

rtr:
  image:
    repository: rtr
    tag: "main"
  service:
    port: 8080

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "apps-dev.hunters.army.mil"
        secretName: "kubedemo-ssl"
        paths:
          - path: "/"
            pathType: ImplementationSpecific

web:
  image:
    repository: web
    tag: "main"
  service:
    port: 8081

api:
  image:
    repository: api
    tag: "main"
  service:
    port: 8082
  persistence:
    enabled: false
    storageClass: "openebs-hostpath"


# environment the environment variables for the deployments
environment:
  API_HOST: "kubedemo-api.kubedemo.svc.cluster.local"

imageCredentials:
  username: "robot"
  password: ""
  registry: "registry.levelup.cce.af.mil"
